# Generated by Django 5.2.4 on 2025-07-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
