# Generated by Django 5.2.4 on 2025-07-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_campaign_category_campaign_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='goal_amount',
        ),
        migrations.AddField(
            model_name='campaign',
            name='amount_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Education', 'Education'), ('Water', 'Water'), ('Food', 'Food'), ('Emergency', 'Emergency')], default='Health', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(default='Default campaign description'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
