# Generated by Django 5.2.4 on 2025-07-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_remove_campaign_goal_amount_campaign_amount_raised_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(),
        ),
    ]
