# Generated by Django 5.2.4 on 2025-07-07 08:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_campaign_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='donations.campaign')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.donor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
